In [36]:
from pymongo import MongoClient
from data_f import *
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import sklearn
import matplotlib
from plot_data import *


%matplotlib inline

In [37]:
first_name = first_name()
last_name = last_name()
usernames = username()
sex = sex()
age = age()
followers = followers()
follows = follows()
media = media()
likes = likes()
comments = comments()
age_classificator = age_classification()

In [38]:
features_dataset = pd.DataFrame(zip(followers, follows, media, 
                                    likes, comments))
training_size = 0.7

features_train = features_dataset[:int(0.7*len(features_dataset))]
features_test = features_dataset[int(0.7*len(features_dataset)):]

labels_train = age_classificator[:int(0.7*len(features_dataset))]
labels_test = age_classificator[int(0.7*len(features_dataset)):]


# Decision Trees 

In [39]:
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(features_train, labels_train)

#print(model)

print(metrics.classification_report(labels_test, model.predict(features_test)))
print(metrics.confusion_matrix(labels_test, model.predict(features_test)))


             precision    recall  f1-score   support

        1.0       0.15      0.21      0.17        57
        2.0       0.77      0.76      0.76       405
        3.0       0.26      0.22      0.24        67
        4.0       0.00      0.00      0.00         7

avg / total       0.63      0.62      0.63       536

[[ 12  41   4   0]
 [ 62 306  36   1]
 [  6  46  15   0]
 [  2   2   3   0]]
